services:
    nginxserver1:
        image: nginximg1:latest
        container_name: nginxcontainer1
        build: 
            context: ./UI1
            dockerfile: Dockerfile
        ports: 
            - "9001"
        volumes:
            - "C:/L/DockerHTML/UI1/conf.d:/etc/nginx/conf.d:ro"
            - "C:/L/DockerHTML/UI1/html:/proxyit1/ui1"
        networks:
            - nginx-network

    nginxserver2:
        image: nginximg2:latest
        container_name: nginxcontainer2
        build: 
            context: ./UI2
        ports: 
            - "9002"
        volumes:
            - "C:/L/DockerHTML/UI2/conf.d:/etc/nginx/conf.d:ro"
            - "C:/L/DockerHTML/UI2/html:/proxyit2/ui2"
        depends_on:
            - nginxserver1
        networks:
            - nginx-network

    proxyserver:
        image: nginxproxyimg:latest
        container_name: nginxproxyservercontainer
        build: 
            context: ./ReverseProxy
        ports: 
            - "8080:9003"
        volumes:
            - "C:/L/DockerHTML/ReverseProxy:/etc/nginx/conf.d:ro"
        depends_on:
            - nginxserver2
        networks:
            - nginx-network

networks:
    nginx-network:
        driver: bridge
